#!/bin/sh

#install aur packages
yay -S rtl8821ce-dkms-git
yay -S ttf-mononoki
yay -S plata-theme
yay -S breeze-purple-cursor-theme
yay -S polybar
yay -S ttf-font-awesome-4
#yay -S libreoffice-extension-languagetool
#yay -S tremc
#yay -S mullvad-vpn
yay -Yc
yay -Sua

