#!/bin/sh
# Arch Linux post-install script

sudo pacman -Syuv

sudo pacman -Sy linux-headers xorg xorg-server xorg-xmodmap xf86-video-intel xorg-xinit xwallpaper xclip light libxcursor
sudo pacman -Sy fontconfig ttf-hanazono ttf-inconsolata ttf-linux-libertine ttf-font-awesome
sudo pacman -Sy pulseaudio pulseaudio-alsa
sudo pacman -Sy bluez bluez-utils
sudo pacman -Sy gtk3 materia-gtk-theme faba-icon-theme
sudo pacman -Sy libnotify neovim bash-completion redshift htop pulsemixer connman wpa_supplicant acpid arandr unclutter
sudo pacman -Sy bspwm sxhkd dunst i3lock-color compton
sudo pacman -Sy python python-pip python-pyperclip
sudo pacman -Sy mpd mpc ncmpcpp
sudo pacman -Sy mpv youtube-dl
sudo pacman -Sy vifm
sudo pacman -Sy gnupg pass
sudo pacman -Sy qutebrowser transmission-cli privoxy dnscrypt-proxy
sudo pacman -Sy sxiv ffmpeg imagemagick maim
sudo pacman -Sy zathura zathura-pdf-mupdf zathura-djvu zathura-cb

sudo pip install bs4
sudo pip install urllib5
sudo pip install ueberzug

#install st
cd ~/.config/st
sudo make clean install

#install dmenu
cd ~/.config/dmenu
sudo make clean install

#install aur packages
yay -S rtl8821ce-dkms-git
yay -S protonvpn-cli
yay -S ttf-mononoki
yay -S vim-plug 
yay -S breeze-blue-cursor-theme
yay -S dasht 
yay -S cht.sh
yay -S qtwebflix
yay -S breeze-blue-cursor-theme
yay -Yc
yay -Sua

sudo systemctl enable acpid.service
sudo systemctl enable connman.service
sudo systemctl enable privoxy.service
sudo systemctl enable dnscrypt-proxy.service
sudo systemctl enable bluetooth.service

sudo ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime
sudo hwclock --systohc --utc

echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "LANG=en_US.UTF-8" >> /etc/environment
locale-gen

sudo chmod +x ~/.scripts/*
sudo chmod +x ~/.config/bspwm/*
sudo chmod +x ~/.config/sxhkd/*

xmodmap ~/.xmodmap

echo "sxhkd &" >> ~/.xinitrc
echo "exec bspwm" >> ~/.xinitrc

# Finish
cd ~/
sudo resolvconf -u

sudo pacman -Syuv
sudo reboot
