#! /bin/sh
#################
### AUTOSTART  ##
#################
killall sxhkd
killall compton
killall redshift
killall dunst
killall polybar
killall unclutter
dunst &
sxhkd &
polybar main &
polybar mon1 &
compton --config $XDG_CONFIG_HOME/appearance/compton.conf &
xautolock -detectsleep -time 5 -locker slock &
#redshift -l 27.950575:-82.457176 -t 6500:3000 &
xrdb ~/.config/appearance/Xresources
xmodmap ~/.config/appearance/Xmodmap
xrandr -output eDP1 --mode 1920x1080
xrandr -output HDMI1 --mode 1920x1080
unclutter -idle 3 &
setbg

################
### MONITORS ###
################
bspc monitor eDP1 -d 4 5 6
bspc monitor HDMI1 -d 1 2 4

############################
#### BSPWM configuration ###
############################
bspc config border_width                3
bspc config top_padding			        40
bspc config bottom_padding		        0
bspc config left_padding		        0
bspc config right_padding		        0
bspc config window_gap                  20
bspc config click_to_focus              true
bspc config split_ratio                 0.50
bspc config top_monocle_padding		    17
bspc config single_monocle              false
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  false

fwid=$(bspc query -N -n focused.automatic)
if [ -n "$fwid" ] ; then
    wattr wh $fwid | {
        read width height
        echo "split_dir=south"
        echo "split_ratio=0.5"
    }
fi

######################
### BSPWM coloring ###
######################
bspc config normal_border_color         "#292d3e"
bspc config focused_border_color        "#c792ea"
bspc config urgent_border_color 	    "#ffcb6b"
bspc config presel_feedback_color	    "#c792ea"

###################
### BSPWM rules ###
###################
