#! /bin/sh
#################
### AUTOSTART  ##
#################
killall sxhkd
killall picom
killall redshift
killall dunst
killall unclutter
doas rfkill unblock bluetooth &
sh ~/.config/polybar/polybar.sh
dunst &
sxhkd &
picom --config $XDG_CONFIG_HOME/appearance/picom.conf &
#xautolock -detectsleep -time 5 -locker slock &
# redshift -l 27.950575:-82.457176 -t 6500:3000 &
xrdb ~/.config/appearance/Xresources
xmodmap ~/.config/appearance/Xmodmap
xrandr -output eDP1 --mode 1920x1080
unclutter -idle 3 &
setbg

################
### MONITORS ###
################
bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDM1 -d 6

############################
#### BSPWM configuration ###
############################
bspc config border_width                2
bspc config top_padding			        50
bspc config bottom_padding		        0
bspc config left_padding		        40
bspc config right_padding		        40
bspc config window_gap                  10
bspc config click_to_focus              true
bspc config split_ratio                 0.50
bspc config top_monocle_padding		    17
bspc config single_monocle              false
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  false

fwid=$(bspc query -N -n focused.automatic)
if [ -n "$fwid" ] ; then
    wattr wh $fwid | {
        read width height
        echo "split_dir=south"
        echo "split_ratio=0.5"
    }
fi

######################
### BSPWM coloring ###
######################
bspc config normal_border_color         "#14161F"
bspc config focused_border_color         "#14161F"
bspc config active_border_color         "#14161F"
bspc config urgent_border_color 	    "#ffcb6b"
bspc config presel_feedback_color	    "#c792ea"

###################
### BSPWM rules ###
###################
bspc rule -a Zathura state=pseudo_tiled
